apiVersion: v1
kind: Service
metadata:
  name: web-cluster-http
  labels:
    app: web-cluster
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - nodePort: 31231
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: web-cluster