apiVersion: v1
kind: Service
metadata:
  name: web-cluster
  labels:
    app: web-cluster
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
  - port: 8228
    name: management
  - port: 16666
    name: akka-remote
  selector:
    app: web-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-cluster
  labels:
    app: web-cluster
spec:
  serviceName: web-cluster
  replicas: 3
  selector:
    matchLabels:
      app: web-cluster
  template:
    metadata:
      labels:
        app: web-cluster
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: web-cluster
        image: webcrawler.web:0.3.0
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER__PORT
          value: "16666"
        - name: CLUSTER__IP
          value: "$(POD_NAME).web-cluster"
        - name: CLUSTER__SEEDS__0
          value: "akka.tcp://webcrawler@lighthouse-0.lighthouse:4053"
        - name: CLUSTER__SEEDS__1
          value: "akka.tcp://webcrawler@lighthouse-1.lighthouse:4053"
        - name: CLUSTER__SEEDS__2
          value: "akka.tcp://webcrawler@lighthouse-2.lighthouse:4053"
        livenessProbe:
          tcpSocket:
            port: 11001
        readinessProbe:
          tcpSocket: 
            port: 80    
        ports:
        - containerPort: 16666
          protocol: TCP
        - containerPort: 80
          protocol: TCP