apiVersion: v1
kind: Service
metadata:
  name: tracker
  labels:
    app: tracker
spec:
  clusterIP: None
  ports:
    - port: 8558
      name: management
    - port: 5055
      name: akka-remote
  selector:
    app: tracker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tracker
  labels:
    app: tracker
    cluster: webcrawler
spec:
  serviceName: tracker
  replicas: 3
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
        cluster: webcrawler
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: tracker
        image: webcrawler.trackerservice:0.3.0
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER__IP
          value: "$(POD_NAME).tracker"
        - name: CLUSTER__PORT
          value: "5055"          
        - name: CLUSTER__STARTUPMETHOD
          value: "KubernetesDiscovery"
        - name: CLUSTER__DISCOVERY__SERVICENAME
          value: "webcrawler"
        - name: CLUSTER__READINESSPORT
          value: "11001"
        - name: CLUSTER__PBMPORT
          value: "9110"
        - name: CLUSTER__ISDOCKER
          value: "true"
        livenessProbe:
          tcpSocket:
            port: 11001
        ports:
          - containerPort: 8558
            protocol: TCP
            name: management
          - containerPort: 5055
            protocol: TCP
            name: akka-remote
