apiVersion: v1
kind: Service
metadata:
  name: web-cluster
  labels:
    app: web-cluster
spec:
  clusterIP: None
  ports:
    - port: 8558
      name: management
    - port: 5055
      name: akka-remote
    - port: 80
      name: http
  selector:
    app: web-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-cluster
  labels:
    app: web-cluster
    cluster: webcrawler
spec:
  serviceName: web-cluster
  replicas: 3
  selector:
    matchLabels:
      app: web-cluster
  template:
    metadata:
      labels:
        app: web-cluster
        cluster: webcrawler
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: web-cluster
        image: webcrawler.web:0.3.0
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER__PORT
          value: "5055"
        - name: CLUSTER__IP
          value: "$(POD_NAME).web-cluster"
        - name: CLUSTER__STARTUPMETHOD
          value: "KubernetesDiscovery"
        - name: CLUSTER__DISCOVERY__SERVICENAME
          value: "webcrawler"
        livenessProbe:
          tcpSocket:
            port: 11001
        readinessProbe:
          tcpSocket: 
            port: 80    
        ports:
          - containerPort: 8558
            protocol: TCP
            name: management
          - containerPort: 5055
            protocol: TCP
            name: akka-remote
          - containerPort: 80
            protocol: TCP
            name: http