apiVersion: v1
kind: Service
metadata:
  name: web-cluster
  labels:
    app: web-cluster
spec:
  clusterIP: None
  ports:
  - port: 8558
    name: management
  - port: 16666
    name: akka-remote
  selector:
    app: web-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: web-cluster-http
  labels:
    app: web-cluster
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - nodePort: 31231
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: web-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-cluster
  labels:
    app: web-cluster
    cluster: webcrawler
spec:
  serviceName: web-cluster
  replicas: 3
  selector:
    matchLabels:
      app: web-cluster
  template:
    metadata:
      labels:
        app: web-cluster
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: web-cluster
        image: webcrawler.web:0.3.0
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).web-cluster"
        livenessProbe:
          tcpSocket:
            port: 16666
        readinessProbe:
          tcpSocket: 
            port: 80    
        ports:
        - containerPort: 8558
        - containerPort: 16666
          protocol: TCP
        - containerPort: 80
          protocol: TCP