apiVersion: v1
kind: Service
metadata:
  name: tracker
  labels:
    app: tracker
spec:
  clusterIP: None
  ports:
  - port: 8558
    name: management
  - port: 5212
    name: akka-remote
  selector:
    app: tracker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tracker
  labels:
    app: tracker
    cluster: webcrawler
spec:
  serviceName: tracker
  replicas: 3
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: tracker
        image: webcrawler.trackerservice:0.3.0
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).tracker"
        livenessProbe:
          tcpSocket:
            port: 5212
        ports:
        - containerPort: 8558
        - containerPort: 5212
          protocol: TCP