apiVersion: v1
kind: Service
metadata:
  name: web-cluster-http
  labels:
    app: web-cluster
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  selector:
    app: web-cluster