apiVersion: v1
kind: Service
metadata:
  name: crawler
  labels:
    app: crawler
spec:
  clusterIP: None
  ports:
  - port: 5213
    name: akka-remote
  - port: 8558
    name: management
  selector:
    app: crawler
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crawler
  labels:
    app: crawler
    cluster: webcrawler
spec:
  serviceName: crawler
  replicas: 3
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: webcrawler.crawlservice:0.3.0
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).crawler"
        - name: CLUSTER_PORT
          value: "5213"
        livenessProbe:
          tcpSocket:
            port: 5213
        ports:
        - containerPort: 8558
          name: management
        - containerPort: 5213
          protocol: TCP